config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/back_office', as: 'rails_admin'
  resources :alerts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  get "visitors/index", as: :home
  mount Payola::Engine => '/payola', as: :payola
  root to: 'visitors#index'
  
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :users
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
  <% else %>
    <h3>You've signed up. Download a free book.</h3>
    <%= link_to 'Download PDF', products_path('product.pdf'), class: 'btn btn-success btn-large' %>
  <% end %>
<% else %>
  <div id="welcome" class="span7">
    <h1>Membership Site</h1>
    <h3>Learn to build a successful subscription site.</h3>
  </div>
  <div class="row col-sm-12 plans">
    <div class="col-sm-3 col-sm-offset-1 well">
      <div class="plan"><h2>Silver</h2></div>
      <ul class="list-unstyled">
        <li>One lesson a month</li>
      </ul>
      <h3>$9/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'silver'), :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-3  col-sm-offset-1 well featured">
      <div class="plan featured-plan"><h2>Gold</h2></div>
      <ul class="list-unstyled">
        <li>Ten lessons a month</li>
      </ul>
      <h3>$19/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'gold'), :class => 'btn btn-primary' %>
    </div>
    <div class="col-sm-3 col-sm-offset-1 well">
      <div class="plan"><h2>Platinum</h2></div>
      <ul class="list-unstyled">
        <li>Thirty lessons a month</li>
      </ul>
      <h3>$29/month</h3>
      <%= link_to 'Subscribe', new_user_registration_path(plan: 'platinum'), :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>