config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/back_office', as: 'rails_admin'
  resources :alerts
  get "content/silver"
  get "content/gold"
  get "content/platinum"
  get "visitors/index", as: :home
  mount Payola::Engine => '/payola', as: :payola
  root to: 'visitors#index'
  
  get 'products/:id', to: 'products#show', :as => :products
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'change_plan', :to => 'registrations#change_plan'
  end
  resources :users
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :user
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  before_action :set_alert, only: [:show, :edit, :update, :destroy]

  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # GET /alerts/1
  # GET /alerts/1.json
  def show
  end

  # GET /alerts/new
  def new
    @alert = Alert.new
  end

  # GET /alerts/1/edit
  def edit
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = Alert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to @alert, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to @alert, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:alert).permit(:user_id, :coin_to_watch, :email, :phone_number, :price_above, :above_currency, :price_below, :below_curency, :data, :active, :alert_type)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/_form.html.erb
<%= simple_form_for @alert, :html => { :class => 'form-horizontal col-md-offset-2 col-md-6' } do |f| %>
  <%= f.hidden_field :user_id %>
  <%= f.error_span(:user_id) %>
  <%= f.input :coin_to_watch %>
  <%= f.error_span(:coin_to_watch) %>
  <%= f.input :alert_type, as: :radio_buttons, collection: ["SMS", "Email"], :label=>"Alert when price is above:" %>
  <%= f.error_span(:alert_type) %>
  <%= f.input :email , as: :email %>
  <%= f.error_span(:email) %>
  <%= f.input :phone_number, as: :tel %>
  <%= f.error_span(:phone_number) %>
  
  <fieldset >
    <legend class="text-muted text-info "> Alert condition rules: </legend>
  <div class="row ">
    <div class="col-md-6">
      <%= f.input :price_above, :class=> "form-control", :hint => "Alert when price is above:" %>
    <%= f.error_span(:price_above) %>
    </div>
    <div class="col-md-offset-1 col-md-3">
      <%= f.input :above_currency, :collection => ["BTC","USD"], :label => "Currency", include_blank: false %>
      <%= f.error_span(:above_currency) %>
    </div>
  </div>
  
  <div class="row ">
    <div class="col-md-6">
      <%= f.input :price_below, :class=> "form-control", :hint => "Alert when price is above:" %>
      <%= f.error_span(:price_below) %>
    </div>
    <div class="col-md-offset-1 col-md-3">
      <%= f.input :below_curency, :collection => ["BTC","USD"], :label => "Currency", include_blank: false %>
      <%= f.error_span(:below_curency) %>
    </div>
  </div>
  
  </fieldset>
  <%#= f.input :data %>
  <%#= error_span(@alert[:data]) %>
  <%= f.input :active,  as: :radio_buttons, collection: ["Active", "Disable"], :label=>"Active or deactivate alert:" %>
  <%= f.error_span(:active) %>
  <%= f.button :submit, :class => 'btn-primary btn-block' %>
  <br/>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                alerts_path, :class => 'btn btn-default' %>
<% end %>

app/views/alerts/edit.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alerts/index.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped  table-responsive table-hover ">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:coin_to_watch) %></th>
      <th><%= model_class.human_attribute_name(:alert_type) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:price_above) %></th>
      <th><%= model_class.human_attribute_name(:price_below) %></th>
      <th><%= model_class.human_attribute_name(:active) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= link_to alert.id, alert_path(alert) %></td>
        <td><%= alert.coin_to_watch %></td>
        <td><%= alert.alert_type %></td>
        <td><%= alert.email %></td>
        <td><%= alert.phone_number %></td>
        <td><%= alert.price_above %></td>
        <td><%= alert.price_below %></td>
        <td><%= alert.active %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      alert_path(alert), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_alert_path(alert), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      alert_path(alert),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_alert_path,
            :class => 'btn btn-primary' %>

app/views/alerts/new.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/alerts/show.html.erb
<%- model_class = Alert -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @alert.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coin_to_watch) %>:</strong></dt>
  <dd><%= @alert.coin_to_watch %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @alert.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @alert.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price_above) %>:</strong></dt>
  <dd><%= @alert.price_above %></dd>
  <dt><strong><%= model_class.human_attribute_name(:above_currency) %>:</strong></dt>
  <dd><%= @alert.above_currency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price_below) %>:</strong></dt>
  <dd><%= @alert.price_below %></dd>
  <dt><strong><%= model_class.human_attribute_name(:below_curency) %>:</strong></dt>
  <dd><%= @alert.below_curency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @alert.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:active) %>:</strong></dt>
  <dd><%= @alert.active %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alert_type) %>:</strong></dt>
  <dd><%= @alert.alert_type %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              alerts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_alert_path(@alert), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              alert_path(@alert),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>